// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBly6R6HsgjLJ7dfHlXjiZA1JjOCYH9QxI',
    appId: '1:19090567488:web:66d483068b32adca738aa5',
    messagingSenderId: '19090567488',
    projectId: 'carbonfootprint-5ef42',
    authDomain: 'carbonfootprint-5ef42.firebaseapp.com',
    storageBucket: 'carbonfootprint-5ef42.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuASkxmY0y1cJxxnWZsNDutTM-rZKZoTk',
    appId: '1:19090567488:android:e34839f9f57c327b738aa5',
    messagingSenderId: '19090567488',
    projectId: 'carbonfootprint-5ef42',
    storageBucket: 'carbonfootprint-5ef42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQchs-aOWXFAHRZO4PhUtmo60YUP4J1Fo',
    appId: '1:19090567488:ios:47cc396604a68a2c738aa5',
    messagingSenderId: '19090567488',
    projectId: 'carbonfootprint-5ef42',
    storageBucket: 'carbonfootprint-5ef42.appspot.com',
    iosBundleId: 'com.carbonapp.carbonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQchs-aOWXFAHRZO4PhUtmo60YUP4J1Fo',
    appId: '1:19090567488:ios:0a92b792750f5815738aa5',
    messagingSenderId: '19090567488',
    projectId: 'carbonfootprint-5ef42',
    storageBucket: 'carbonfootprint-5ef42.appspot.com',
    iosBundleId: 'com.carbonapp.carbonApp.RunnerTests',
  );
}
